spring:
  application:
    name: bada-on-be
  datasource:
    url: ${DATABASE_URL}?allowPublicKeyRetrieval=true&useSSL=false
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: root

  #    url: jdbc:mariadb://localhost:3306/badaon
  #    username: root
  #    password: 1234
  #    driver-class-name: org.mariadb.jdbc.Driver

  #    driver-class-name: org.h2.Driver
  #    url: jdbc:h2:mem:test
  #    username: sa
  #    password:
  #  h2:
  #    console:
  #      enabled: true
  jpa:
    hibernate:
      ddl-auto: none
    #      ddl-auto: create
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
  output:
    ansi:
      enabled: always
logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql: trace